#!/bin/bash

go mod tidy
mkdir -p views
echo "" > views/test.html
./epoch render
cp main.go save_main
cp wasm/main.go .
GOOS=js GOARCH=wasm go build -ldflags="-s -w -X main.useLive=true" -o assets/other/json.wasm

if [ $? -eq 0 ]; then
  cd assets/other
  rm json.wasm.gz
  gzip json.wasm
  cd ../..
  mv save_main main.go
  tailwindcss -i assets/css/tail.components.css -o assets/css/tail.min.css --minify
  export uuid=$(uuidgen)
  go build -ldflags="-X main.buildTag=$uuid" -o epoch
  if [ $? -eq 0 ]; then
    echo 3
    DATABASE_URL=postgres://fred3:fred3@localhost/book?sslmode=disable
    ./epoch run
  else
    mv save_main main.go
    git checkout main.go
    echo "false"
  fi
else
  echo "false"
fi
