#!/bin/bash

go mod tidy
mkdir -p views
./epoch render
cp main.go save_main
cp wasm/main.go .
ENV_VAR="$EPOCH_GUI"
if [ "$ENV_VAR" = "1" ]; then
  GOOS=js GOARCH=wasm go build -ldflags="-s -w -X main.useLive=false" -o assets/other/json.wasm
else
  GOOS=js GOARCH=wasm go build -ldflags="-s -w -X main.useLive=true" -o assets/other/json.wasm
fi

if [ $? -eq 0 ]; then
  cd assets/other
  rm json.wasm.gz
  gzip json.wasm
  cd ../..
  mv save_main main.go
  tailwindcss -i assets/css/tail.components.css -o assets/css/tail.min.css --minify
  export uuid=$(uuidgen)
  go build -ldflags="-X main.buildTag=$uuid" -o epoch
  if [ $? -eq 0 ]; then
    echo 3
    if [ "$ENV_VAR" = "1" ]; then
      echo 4
      mkdir -p epoch.app/Contents/MacOS
      mkdir -p epoch.app/Contents/Resources
      cp epoch epoch.app/Contents/MacOS/
      cp ~/Documents/epoch epoch.app/Contents/Resources
    else
      echo 6
      ./epoch run
    fi
  else
    mv save_main main.go
    git checkout main.go
    echo "false"
  fi
else
  echo "false"
fi
